name: .NET

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CONFIGURATION: Release
      MYGET_API_KEY: ${{ secrets.MYGET_API_KEY }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore
      run: dotnet restore --locked-mode

    - name: Build
      run: dotnet build --configuration ${CONFIGURATION} --no-restore -p:ContinuousIntegrationBuild=true

    - name: Test
      run: dotnet test --configuration ${CONFIGURATION} --no-restore --no-build --collect:"XPlat Code Coverage" --settings CI.runsettings

    - name: Push
      run: dotnet nuget push src/Aetos.ComparisonGenerator/bin/${CONFIGURATION}/Aetos.ComparisonGenerator.*.nupkg --source https://www.myget.org/F/aetos/api/v2/package --api-key ${MYGET_API_KEY}
