name: CI

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04
    env:
      CONFIGURATION: Release

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore
      run: dotnet restore --locked-mode

    - name: Build
      run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore --no-incremental -p:ContinuousIntegrationBuild=true

    - name: Test
      run: dotnet test --configuration ${{ env.CONFIGURATION }} --no-restore --no-build --collect "XPlat Code Coverage" --settings CI.runsettings --logger junit

    - name: Collect coverage reports
      id: coverage_reports
      shell: pwsh
      run: |-
        $files = Get-ChildItem -Filter coverage.opencover.xml -Recurse -File -Name
        echo "::set-output name=files::$($files -join ',')"

    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: ${{ steps.coverage_reports.outputs.files }}

    - name: Push Package
      env:
        MYGET_API_KEY: ${{ secrets.MYGET_API_KEY }}
      run: dotnet nuget push src/Aetos.ComparisonGenerator/bin/${{ env.CONFIGURATION }}/Aetos.ComparisonGenerator.*.nupkg --source https://www.myget.org/F/aetos/api/v2/package --api-key ${{ env.MYGET_API_KEY }}

    - name: Publish test report
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: '**/TestResults.xml'
        report_individual_runs: true
        check_run_annotations: all tests, skipped tests

    - uses: actions/upload-artifact@v2
      with:
        name: nuget-package
        path: '**/*.nupkg'

    - uses: actions/upload-artifact@v2
      with:
        name: sarif
        path: sarif/
