name: .NET

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CONFIGURATION: Release

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore
      run: dotnet restore --locked-mode

    - name: Build
      run: dotnet build --configuration ${CONFIGURATION} --no-restore -p:ContinuousIntegrationBuild=true

    - name: Test
      run: dotnet test --configuration ${CONFIGURATION} --no-restore --no-build --collect:"XPlat Code Coverage" --settings CI.runsettings --logger junit

    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: '**/coverage.opencover.xml'
        flags: unittests
        fail_ci_if_error: true

    - name: Publish test report
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: '**/TestResults.xml'
        report_individual_runs: true
        check_run_annotations: all tests, skipped tests

    - name: SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Push Package
      env:
        MYGET_API_KEY: ${{ secrets.MYGET_API_KEY }}
      run: dotnet nuget push src/Aetos.ComparisonGenerator/bin/${CONFIGURATION}/Aetos.ComparisonGenerator.*.nupkg --source https://www.myget.org/F/aetos/api/v2/package --api-key ${MYGET_API_KEY}
