name: CI

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04
    env:
      CONFIGURATION: Release

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore
      run: dotnet restore --locked-mode

    - name: Build
      run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore --no-incremental -p:ContinuousIntegrationBuild=true

    - name: Test
      run: dotnet test --configuration ${{ env.CONFIGURATION }} --no-restore --no-build --collect "XPlat Code Coverage" --settings CI.runsettings --logger junit

    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: '**/coverage.opencover.xml'
        flags: unittests
        fail_ci_if_error: true

    - name: Publish test report
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: '**/TestResults.xml'
        report_individual_runs: true
        check_run_annotations: all tests, skipped tests

    - name: Collect coverage reports
      id: coverage_reports
      shell: pwsh
      run: |-
        $files = Get-ChildItem -Filter coverage.opencover.xml -Recurse -File -Name
        echo "::set-output name=files::$($files -join ',')"

    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: ${{ steps.coverage_reports.outputs.files }}

    - name: Push Package
      env:
        MYGET_API_KEY: ${{ secrets.MYGET_API_KEY }}
      run: dotnet nuget push src/Aetos.ComparisonGenerator/bin/${{ env.CONFIGURATION }}/Aetos.ComparisonGenerator.*.nupkg --source https://www.myget.org/F/aetos/api/v2/package --api-key ${{ env.MYGET_API_KEY }}

    - uses: actions/upload-artifact@v2
      with:
        name: nuget-package
        path: '**/*.nupkg'

    # Execute Codacy Analysis CLI and generate a SARIF output with the security issues identified during the analysis
    - name: Run Codacy Analysis CLI
      uses: codacy/codacy-analysis-cli-action@1.1.0
      with:
        # Check https://github.com/codacy/codacy-analysis-cli#project-token to get your project token from your Codacy repository
        # You can also omit the token and run the tools that support default configurations
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        verbose: true
        output: results.sarif
        format: sarif
        # Adjust severity of non-security issues
        gh-code-scanning-compat: true
        # Force 0 exit code to allow SARIF file generation
        # This will handover control about PR rejection to the GitHub side
        max-allowed-issues: 2147483647

    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: .
